// The lint gate. Flat config, because ESLint 9 no longer reads .eslintrc by default.
//
// WHAT THIS IS AND IS NOT. Every dependency it needs was ALREADY installed — eslint 9.39.4,
// eslint-config-next 15.5.19, @typescript-eslint 8.61.1, eslint-plugin-react-hooks — and a
// `lint` script already existed. So this is not adopting a linter. It is adding the one file
// that was missing, and replacing a script that promised a gate it did not run.
//
// `next lint` IS NOT USED, and that is deliberate rather than stylistic. Next 15.5.19's own
// CLI prints "`next lint` is deprecated and will be removed in Next.js 16" and points at the
// ESLint CLI. Its scaffold also writes `.eslintrc.json`, the legacy format. So the gate runs
// `eslint .` directly, from package.json and from CI, which is #183's rule applied again —
// COMMIT THE TOOL so CI and humans run the same command and cannot disagree.
//
// FlatCompat, because eslint-config-next@15 is still eslintrc-style internally
// (`module.exports = { extends: [...] }`). @eslint/eslintrc ships with eslint and needed no
// install.
//
// NO CONFIG-LEVEL RULE DISABLES, and that is a finding rather than an omission.
// `@next/next/no-img-element` was expected to need one for the locked plain-`<img>` decision.
// It does not: the rule is `warn` (it comes from the plugin's `recommended` set, NOT from
// core-web-vitals, which only raises no-html-link-for-pages and no-sync-scripts to error),
// and it reports ZERO because all five plain-`<img>` sites already carry inline disables.
// The codebase was written as if lint were on — 13 inline disables predate this file — so the
// gate confirms existing practice rather than imposing a new standard. Keep it that way:
// prefer an inline disable WITH A REASON at the site over a rule turned off for everyone.
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

// Named rather than exported anonymously, which `import/no-anonymous-default-export` asks
// for — the config lints itself, and a gate that exempts its own configuration is not one.
const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "public/**",
      // Design references and explorations, not source. Six of them are untracked.
      "docs/**",
      // RALPH IS TEST CODE WITH ITS OWN RUNNER AND ITS OWN VERDICT — the exit code. Linting
      // it adds nothing a failing suite does not already say louder.
      //
      // It is also the SAME BOUNDARY #177 DREW when it excluded ralph from Tailwind's
      // scanner, for the same reason: it is not application source. And it runs under
      // `--experimental-strip-types`, a different resolution model from the app.
      //
      // Concretely: 22 of its 26 warnings were one shared line, `ok ? pass++ : fail++`, the
      // assertion helper every suite carries. "Fixing" that means rewriting the idiom across
      // 32 suites — a large, risky diff through the entire proof layer to satisfy a
      // stylistic rule.
      "ralph/**",
      // GENERATED BY NEXT on every build, and its `triple-slash-reference` error is not
      // fixable by hand — Next rewrites the file. An ignore is the only honest treatment.
      "next-env.d.ts",
    ],
  },
  // What `next lint` itself recommends for a repo with a tsconfig.json, read out of
  // next/dist/lib/eslint/getESLintPromptValues.js rather than assumed.
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
