// Blog PR 3b — the blog write seam. Read-modify-write serialization for a post file.
//
// SHAPE, decided by experiment rather than by analogy with projects. Two candidates were
// run against the real content file and against a hand-authored one:
//
//   candidate                 no-op on the real post   one-field edit   no-op on a HAND-AUTHORED post
//   whole-file load -> dump   identical                1 line           REFORMATS the blocks tail
//   split at "\nblocks:"      identical                1 line           tail preserved verbatim
//
// They are indistinguishable on the current file — it was generated by dump() in #171,
// so it is already js-yaml canonical. They diverge exactly where the projects lesson
// lives: a hand-authored file with a literal `|` scalar gets silently rewritten by the
// naive dump. So this takes the SPLICE, and carries the refuse-rather-than-reformat
// posture with it.
//
// WHY THE SPLICE IS DUPLICATED HERE rather than extracted from projects-serialize /
// sections-serialize: it is eight lines of indexOf and slice with no algorithm that can
// drift, and keeping those two files UNTOUCHED in the riskiest PR of the arc is worth
// more than deleting the duplication. (The field COMBINATORS, which carry real
// validation logic and CAN drift, are shared — see blog-format.ts.) Extract on the third
// collection.
//
// BLOG IS SIMPLER THAN PROJECTS and does not inherit its complexity: projects splits at
// TWO keys (`\nbody:` for the head path, `\nsections:` for the tail path) because it
// carries a vestigial `body` alongside `sections`. Blog has ONE tail key, so a single
// split point serves both directions.
//
// Only js-yaml + type-only imports, so it is unit-exercisable directly.
import { load, dump, type DumpOptions } from "js-yaml";
import type { BlogInput, BlogCreateInput } from "./blog-format";
import type { SaveError } from "./site-settings-format";

export type SerializeResult = { ok: true; bytes: string } | { ok: false; error: SaveError };

/**
 * TRANSPORT-INDEPENDENCE. js-yaml emits `&ref_0`/`*ref_0` anchors whenever two keys hold
 * the SAME OBJECT REFERENCE — a property of the input object graph, not of its values.
 * That makes the dump depend on how the data arrived: `load()` restores the file's shared
 * refs, while the route's `JSON.parse(body)` has none. `noRefs` makes the output a
 * function of values alone, so both paths agree. (sections-serialize documents the same
 * hazard; blog would hit it identically the first time a save round-tripped.)
 */
const DUMP_OPTIONS: DumpOptions = { noRefs: true };

/**
 * The dump options that reproduce a blog HEAD. ONE candidate, unlike projects' two —
 * projects carries a second (`{ lineWidth: -1, quotingType: '"' }`) to match
 * experience-shaped files already on disk, which is not a general truth and not blog's
 * situation. Verified against the real post: `{ noRefs: true }` reproduces its head
 * byte-for-byte, including `date: '2026-07-24'` (js-yaml quotes it to keep it a STRING —
 * lose that and the next load yields a Date, and the read path's lexical date sort would
 * be comparing a Date against strings).
 */
const HEAD_DUMP_CANDIDATES: DumpOptions[] = [{ noRefs: true }];

/** The head keys in canonical schema order (keystatic.config's blog collection). The
 *  head is rebuilt in THIS order, so a patch that adds a previously-absent optional key
 *  (e.g. a first `topic`) puts it in its schema position rather than appending it.
 *
 *  ⚠ THIS IS AN ORDERING LIST AND NOT A FILTER, AND THE DIFFERENCE IS THE WHOLE REASON THE
 *  FALLTHROUGH BELOW EXISTS. It used to filter — the head was built from these six keys and
 *  nothing followed — so A KEY ADDED TO THE BLOG SCHEMA AND NOT TO THIS LINE WAS SILENTLY
 *  DROPPED ON SAVE. That is gallery's exact mechanism, in the collection with no browser run
 *  on record, and `collection-readiness` C2 is what found it.
 *
 *  ⚠ AND THE SECOND FILTER GUARDED NOTHING, WHICH IS WHY THE FIX IS A DELETION RATHER THAN A
 *  GATE. `sanitizeBlogPatch` is a per-key allowlist that rejects `blocks` by name and ends
 *  `return bad("unknown field …")` with a 400, and `PATCH_SANITIZERS[collection]` and
 *  `commitCollectionEntry(collection, …)` are indexed by ONE variable — so the cast at
 *  commit-collection-entry.ts:232 is guarded and `patch` provably carries only `BlogInput`
 *  keys. `current` is head-only because `splitAtBlocks` cuts before `blocks:`. There was no
 *  key for this list to stop.
 *
 *  ⚠ THE COST, NAMED BECAUSE A FILTERING LIST IS ALSO A FORMATTING DECISION: a FUTURE schema
 *  key is APPENDED rather than placed. Add it to this line and it sits in schema position;
 *  forget, and the file is correct with one key out of order. Before, forgetting lost the
 *  value. A formatting cost for a data cost is the trade, and it is the right way round.
 *
 *  ⚠ AND IT RECOVERS THE HAND-EDIT ROUTE, WHICH THIS REPOSITORY HAS SEEN. Four project-shaped
 *  files carrying a key the schema never had reached main by a path nobody expected. A post
 *  hand-edited to hold an extra key used to lose it on the owner's next save, silently. */
const BLOG_HEAD_KEYS = ["title", "dek", "date", "topic", "status", "heroImage"] as const;

const unsupported = (message: string): SerializeResult => ({
  ok: false,
  error: { code: "unsupported_format", message },
});

/**
 * Split a post file at the top-level `blocks:` key. `blocks` is the LAST top-level key in
 * the schema, and every nested line is indented, so `\nblocks:` matches only the key
 * itself (the same reasoning splitAtBody/splitAtSections use).
 */
function splitAtBlocks(raw: string): { head: string; blocks: string } | null {
  const i = raw.indexOf("\nblocks:");
  if (i === -1) return null;
  return { head: raw.slice(0, i + 1), blocks: raw.slice(i + 1) };
}

/** Round-trip the head to find the options that reproduce it. Null when none does — the
 *  caller then REFUSES rather than reformatting content nobody asked it to touch. */
function detectHeadOptions(head: string): DumpOptions | null {
  const loaded = load(head) ?? {};
  for (const opts of HEAD_DUMP_CANDIDATES) {
    if (dump(loaded, opts) === head) return opts;
  }
  return null;
}

/** Read a post file's current `blocks` value. [] when the file has no blocks key. */
export function readBlogBlocks(raw: string): unknown[] {
  const doc = (load(raw) ?? {}) as { blocks?: unknown };
  return Array.isArray(doc.blocks) ? doc.blocks : [];
}

/**
 * Apply a sanitized head patch, preserving the `blocks` tail VERBATIM and every
 * unchanged head field byte-for-byte. A no-op patch reproduces the file exactly.
 *
 * Refuses (unsupported_format) when the file has no `blocks:` key, or when no candidate
 * reproduces its head — we refuse rather than reformat content the owner did not edit.
 */
export function serializeBlogEntry(raw: string, patch: Partial<BlogInput>): SerializeResult {
  const split = splitAtBlocks(raw);
  if (!split) return unsupported("this file has no blocks key; it is not a blog post");
  const opts = detectHeadOptions(split.head);
  if (!opts) return unsupported("this post's head is not in the expected format");

  const current = (load(split.head) ?? {}) as Record<string, unknown>;
  const patched = patch as Record<string, unknown>;

  // Rebuilt in declared order, so the dump is stable no matter what order the client
  // sent — and an optional key that was absent lands in its schema position.
  const head: Record<string, unknown> = {};
  for (const key of BLOG_HEAD_KEYS) {
    if (Object.prototype.hasOwnProperty.call(patched, key)) {
      head[key] = patched[key];
    } else if (Object.prototype.hasOwnProperty.call(current, key)) {
      // hasOwnProperty, not a truthiness check: `heroImage: null` is a VALUE (Keystatic
      // writes an absent image as null), not an absence, and must survive.
      head[key] = current[key];
    }
  }

  // ⚠ THE FALLTHROUGH — every key the list does not name, appended in the order the FILE
  // already had it. Without this the loop above is a filter and an unlisted key is lost on
  // save; `serializeExperience` has had this shape all along, which is why `experience`
  // reports ORDERING ONLY where blog reported UNGUARDED.
  //
  // Same precedence as above and for the same reason: the patch wins, else the current file,
  // and `hasOwnProperty` rather than truthiness so an explicit `null` survives.
  for (const key of Object.keys({ ...current, ...patched })) {
    if (key in head) continue;
    head[key] = Object.prototype.hasOwnProperty.call(patched, key) ? patched[key] : current[key];
  }

  return { ok: true, bytes: dump(head, opts) + split.blocks };
}

/**
 * Write a new `blocks` value, preserving the head byte-for-byte. The caller supplies the
 * FULL array (the editor reads all of it, edits one field, writes it back), so unedited
 * blocks are re-dumped from the exact values they were read as — never retyped.
 *
 * The head is NOT re-dumped here (it is spliced through untouched), so this needs no
 * candidate detection — only the `blocks:` key has to exist.
 */
export function serializeBlogBlocks(raw: string, blocks: unknown[]): SerializeResult {
  const split = splitAtBlocks(raw);
  if (!split) return unsupported("this file has no blocks key; it is not a blog post");
  return { ok: true, bytes: split.head + dump({ blocks }, DUMP_OPTIONS) };
}

/**
 * Serialize a NEW post: the head in schema order plus an empty `blocks: []`.
 *
 * ALWAYS `status: draft` — the sanitizer refuses a client-supplied status for this
 * reason. Whole-branch publish means a new post reaches main the next time anything is
 * published, so being born published would put an empty post on the live site. Going
 * live is a deliberate later edit.
 *
 * `heroImage: null` is written explicitly (matching what Keystatic writes for an unset
 * image, and what the existing post carries) rather than omitted, so the head shape is
 * the same on day one as after the first upload.
 */
export function serializeNewBlogPost(input: BlogCreateInput): SerializeResult {
  const entry: Record<string, unknown> = {
    title: input.title,
    dek: input.dek,
    date: input.date,
    ...(input.topic !== undefined ? { topic: input.topic } : {}),
    status: "draft",
    heroImage: null,
    blocks: [] as unknown[],
  };
  return { ok: true, bytes: dump(entry, DUMP_OPTIONS) };
}
